version: "3.9"
services:
  app:
    build: .
    # docker node Cannot find module '../build/Release/sharp-linux-arm64v8.node'の回避のため
    platform: linux/x86_64
    command: npm run dev
    environment:
      AWS_REGION: "ap-northeast-1"
      AWS_ACCESS_KEY_ID: "sample"
      AWS_SECRET_ACCESS_KEY: "sample"
      S3_BUCKET_NAME: "shuntagami-demo-data"
      S3_ENDPOINT: http://s3:4566
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
  s3:
    image: localstack/localstack
    environment:
      SERVICES: s3
      DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /var/lib/localstack/data
    volumes:
      - ./localstack:/var/lib/localstack
      - ./aws:/etc/localstack/init/ready.d
    ports:
      - 4566:4566
