version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/workspace
    working_dir: /workspace/app
    ports:
      - "3001:3001"
    ulimits:
      nofile:
        soft: 500
        hard: 500
